# OCLOCK - Page par defaut
app:
    path:     /
    defaults: { _controller: AppBundle:Security:login }

# OCLOCK - Formulaire d'authentification

login:
    path:     login
    defaults: { _controller: AppBundle:Security:login }

# OCLOCK - Deconnexion utilisateur
logout:
    path: /logout

# OCLOCK - Creation d'un nouvel utilisateur

user_registration:
    path:     register
    defaults: { _controller: AppBundle:Registration:register }

# OCLOCK - Gestion utilisateur
owner_profile:
    path:    owner/profile
    defaults: { _controller: AppBundle:Owner:profile }

owner_add_pet:
    path:    owner/add_pet
    defaults: { _controller: AppBundle:Owner:addPet }
